# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/ubuntu-20-dev:main
      options:
        --user 1018
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /mnt/raid10/github-ci/download:/home/dev/dl:Z
        -v /mnt/raid10/github-ci/sstate/yocto/honister/rpi4-drm/latest:/home/dev/sstate:Z
        -v /mnt/raid10/github-ci/artifacts/rpi4/drm:/home/dev/artifacts:Z

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Build
      run: |
        [ -d ../rpi4-drm-honister-latest ] || mkdir -p ../rpi4-drm-honister-latest
        cd ../rpi4-drm-honister-latest
        git config --list
        git config --global user.email tvsarathy@gmail.com
        git config --global user.name "Vijayasarathy
        git config --list
        git clone https://github.com/tvijayas/flutter-yocto-setup-build.git
        cd flutter-yocto-setup-build
        ./raspberryPi4-64-flutter-setup-build.sh
